<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title>BUYSELL</title>
    </head>
    <body>
        <h1>База Данных Well Manager</h1><hr>
        <input type="button" value="Исходные данные" onclick="window.location.href='/init'"><br>
        <input type="button" value="Менеджер данных" onclick="window.location.href='/pump-card'"><br>
        <input type="button" value="Визуализация данных" ><br>
    </body>
</html>